services:
  # Service Web Django
  - type: web
    name: fmos-mfmc
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py creer_superuser --username Soul --email souley.mfmc@outlook.fr --password Yiriba_19 && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 2 --worker-class sync --max-requests 1000 --max-requests-jitter 100
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: ALLOWED_HOSTS
        value: fmos-mfmc.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: fmos-mfmc-db
          property: connectionString
    healthCheckPath: /

databases:
  # Base de donn√©es PostgreSQL
  - name: fmos-mfmc-db
    plan: free
    databaseName: fmos_mfmc
    user: fmos_mfmc_user

